import type {
  LonePairRecord,
  MoleculeAtom,
  MoleculeBond,
  MoleculeRecord,
  QuizQuestion,
  VseprElectronGeometry,
  VseprMolecularGeometry,
} from "./types";
import {
  calculateNetDipole,
  generateVsepr3DPositions,
  VSEPR_TEMPLATES,
} from "./vsepr";
import { elements } from "./elements";

const ELEMENT_MAP = new Map(elements.map((e) => [e.symbol, e]));

export const MOLECULE_CATEGORIES = [
  { id: "all", label: "All molecules" },
  { id: "vsepr-essential", label: "VSEPR geometries" },
  { id: "atmospheric", label: "Atmospheric & gases" },
  { id: "organic", label: "Organic compounds" },
  { id: "biomolecule", label: "Biomolecules" },
] as const;

export const curatedMolecules: MoleculeRecord[] = [
  {
    slug: "water",
    name: "Water",
    iupacName: "Oxidane",
    formula: "H₂O",
    category: "vsepr-essential",
    categoryLabel: "VSEPR Geometry",
    description: "The universal solvent essential to all known life. Two lone pairs on oxygen compress the H–O–H bond angle from the ideal 109.5° tetrahedron down to 104.5°.",
    molarMass: 18.015,
    standardState: "liquid",
    meltingPoint: 273.15,
    boilingPoint: 373.15,
    density: "1.00 g/cm³",
    vsepr: {
      axeNotation: "AX₂E₂",
      stericNumber: 4,
      bondingPairs: 2,
      lonePairs: 2,
      electronGeometry: "Tetrahedral",
      molecularGeometry: "Bent (104.5°)",
      idealBondAngle: "109.5°",
      predictedBondAngle: "104.5°",
      hybridization: "sp³",
      polarity: "Polar",
      dipoleMomentDebye: 1.85,
      dipoleVector: [0, 1, 0],
    },
    atoms: [
      { id: "O1", symbol: "O", atomicNumber: 8, position: [0, 0.12, 0], isCentral: true },
      { id: "H1", symbol: "H", atomicNumber: 1, position: [0.76, -0.48, 0] },
      { id: "H2", symbol: "H", atomicNumber: 1, position: [-0.76, -0.48, 0] },
    ],
    bonds: [
      { from: "O1", to: "H1", order: 1 },
      { from: "O1", to: "H2", order: 1 },
    ],
    lonePairs: [
      { id: "LP1", centralAtomId: "O1", position: [0, 0.65, 0.62] },
      { id: "LP2", centralAtomId: "O1", position: [0, 0.65, -0.62] },
    ],
    lewis: {
      atoms: [
        { atomId: "O1", symbol: "O", x: 100, y: 80, lonePairAngles: [90, 270] },
        { atomId: "H1", symbol: "H", x: 155, y: 110, lonePairAngles: [] },
        { atomId: "H2", symbol: "H", x: 45, y: 110, lonePairAngles: [] },
      ],
      bonds: [
        { fromAtomId: "O1", toAtomId: "H1", order: 1 },
        { fromAtomId: "O1", toAtomId: "H2", order: 1 },
      ],
    },
    applications: "Universal solvent, biological cellular medium, thermal buffering in climate and oceans.",
    safety: "Non-toxic, safe. Essential nutrient for living organisms.",
    relatedElements: [1, 8],
  },
  {
    slug: "carbon-dioxide",
    name: "Carbon Dioxide",
    iupacName: "Carbon dioxide",
    formula: "CO₂",
    category: "vsepr-essential",
    categoryLabel: "VSEPR Geometry",
    description: "A linear triatomic molecule with two double bonds. Because both bond dipoles pull with equal magnitude in exact opposite directions (180°), the net dipole moment is zero, making CO₂ completely non-polar.",
    molarMass: 44.009,
    standardState: "gas",
    meltingPoint: 194.7, // sublimation
    boilingPoint: 194.7,
    density: "1.98 kg/m³",
    vsepr: {
      axeNotation: "AX₂",
      stericNumber: 2,
      bondingPairs: 2,
      lonePairs: 0,
      electronGeometry: "Linear",
      molecularGeometry: "Linear",
      idealBondAngle: "180°",
      predictedBondAngle: "180°",
      hybridization: "sp",
      polarity: "Non-polar",
      dipoleMomentDebye: 0.0,
      dipoleVector: [0, 0, 0],
    },
    atoms: [
      { id: "C1", symbol: "C", atomicNumber: 6, position: [0, 0, 0], isCentral: true },
      { id: "O1", symbol: "O", atomicNumber: 8, position: [1.16, 0, 0] },
      { id: "O2", symbol: "O", atomicNumber: 8, position: [-1.16, 0, 0] },
    ],
    bonds: [
      { from: "C1", to: "O1", order: 2 },
      { from: "C1", to: "O2", order: 2 },
    ],
    lonePairs: [
      { id: "LP1", centralAtomId: "O1", position: [1.6, 0.5, 0] },
      { id: "LP2", centralAtomId: "O1", position: [1.6, -0.5, 0] },
      { id: "LP3", centralAtomId: "O2", position: [-1.6, 0.5, 0] },
      { id: "LP4", centralAtomId: "O2", position: [-1.6, -0.5, 0] },
    ],
    lewis: {
      atoms: [
        { atomId: "C1", symbol: "C", x: 100, y: 80, lonePairAngles: [] },
        { atomId: "O1", symbol: "O", x: 160, y: 80, lonePairAngles: [0, 90] },
        { atomId: "O2", symbol: "O", x: 40, y: 80, lonePairAngles: [180, 270] },
      ],
      bonds: [
        { fromAtomId: "C1", toAtomId: "O1", order: 2 },
        { fromAtomId: "C1", toAtomId: "O2", order: 2 },
      ],
    },
    applications: "Plant photosynthesis carbon substrate, carbonation in beverages, refrigeration (dry ice), fire extinguishing agent.",
    safety: "Asphyxiant in high concentrations; major planetary greenhouse gas.",
    relatedElements: [6, 8],
  },
  {
    slug: "ammonia",
    name: "Ammonia",
    iupacName: "Azane",
    formula: "NH₃",
    category: "vsepr-essential",
    categoryLabel: "VSEPR Geometry",
    description: "Trigonal pyramidal molecule with one lone pair. The single lone pair repels the three N–H bonding pairs, tightening the bond angle to 107.0° and creating a strong net dipole.",
    molarMass: 17.031,
    standardState: "gas",
    meltingPoint: 195.42,
    boilingPoint: 239.81,
    density: "0.73 kg/m³",
    vsepr: {
      axeNotation: "AX₃E",
      stericNumber: 4,
      bondingPairs: 3,
      lonePairs: 1,
      electronGeometry: "Tetrahedral",
      molecularGeometry: "Trigonal Pyramidal",
      idealBondAngle: "109.5°",
      predictedBondAngle: "107.0°",
      hybridization: "sp³",
      polarity: "Polar",
      dipoleMomentDebye: 1.47,
      dipoleVector: [0, 1, 0],
    },
    atoms: [
      { id: "N1", symbol: "N", atomicNumber: 7, position: [0, 0.18, 0], isCentral: true },
      { id: "H1", symbol: "H", atomicNumber: 1, position: [0.94, -0.28, 0] },
      { id: "H2", symbol: "H", atomicNumber: 1, position: [-0.47, -0.28, 0.81] },
      { id: "H3", symbol: "H", atomicNumber: 1, position: [-0.47, -0.28, -0.81] },
    ],
    bonds: [
      { from: "N1", to: "H1", order: 1 },
      { from: "N1", to: "H2", order: 1 },
      { from: "N1", to: "H3", order: 1 },
    ],
    lonePairs: [
      { id: "LP1", centralAtomId: "N1", position: [0, 0.95, 0] },
    ],
    lewis: {
      atoms: [
        { atomId: "N1", symbol: "N", x: 100, y: 75, lonePairAngles: [90] },
        { atomId: "H1", symbol: "H", x: 100, y: 130, lonePairAngles: [] },
        { atomId: "H2", symbol: "H", x: 55, y: 95, lonePairAngles: [] },
        { atomId: "H3", symbol: "H", x: 145, y: 95, lonePairAngles: [] },
      ],
      bonds: [
        { fromAtomId: "N1", toAtomId: "H1", order: 1 },
        { fromAtomId: "N1", toAtomId: "H2", order: 1 },
        { fromAtomId: "N1", toAtomId: "H3", order: 1 },
      ],
    },
    applications: "Key precursor to synthetic fertilizers (Haber-Bosch process), household cleaners, industrial refrigeration.",
    safety: "Pungent, irritating vapor. Corrosive to mucous membranes and toxic if inhaled in high amounts.",
    relatedElements: [1, 7],
  },
  {
    slug: "methane",
    name: "Methane",
    iupacName: "Methane",
    formula: "CH₄",
    category: "vsepr-essential",
    categoryLabel: "VSEPR Geometry",
    description: "The classic regular tetrahedral molecule. Four equivalent C–H single bonds point toward the vertices of a regular tetrahedron at 109.5° angles, canceling all bond dipoles completely.",
    molarMass: 16.043,
    standardState: "gas",
    meltingPoint: 90.7,
    boilingPoint: 111.66,
    density: "0.656 kg/m³",
    vsepr: {
      axeNotation: "AX₄",
      stericNumber: 4,
      bondingPairs: 4,
      lonePairs: 0,
      electronGeometry: "Tetrahedral",
      molecularGeometry: "Tetrahedral",
      idealBondAngle: "109.5°",
      predictedBondAngle: "109.5°",
      hybridization: "sp³",
      polarity: "Non-polar",
      dipoleMomentDebye: 0.0,
      dipoleVector: [0, 0, 0],
    },
    atoms: [
      { id: "C1", symbol: "C", atomicNumber: 6, position: [0, 0, 0], isCentral: true },
      { id: "H1", symbol: "H", atomicNumber: 1, position: [0, 1.09, 0] },
      { id: "H2", symbol: "H", atomicNumber: 1, position: [1.03, -0.36, 0] },
      { id: "H3", symbol: "H", atomicNumber: 1, position: [-0.51, -0.36, 0.89] },
      { id: "H4", symbol: "H", atomicNumber: 1, position: [-0.51, -0.36, -0.89] },
    ],
    bonds: [
      { from: "C1", to: "H1", order: 1 },
      { from: "C1", to: "H2", order: 1 },
      { from: "C1", to: "H3", order: 1 },
      { from: "C1", to: "H4", order: 1 },
    ],
    lonePairs: [],
    lewis: {
      atoms: [
        { atomId: "C1", symbol: "C", x: 100, y: 80, lonePairAngles: [] },
        { atomId: "H1", symbol: "H", x: 100, y: 30, lonePairAngles: [] },
        { atomId: "H2", symbol: "H", x: 100, y: 130, lonePairAngles: [] },
        { atomId: "H3", symbol: "H", x: 50, y: 80, lonePairAngles: [] },
        { atomId: "H4", symbol: "H", x: 150, y: 80, lonePairAngles: [] },
      ],
      bonds: [
        { fromAtomId: "C1", toAtomId: "H1", order: 1 },
        { fromAtomId: "C1", toAtomId: "H2", order: 1 },
        { fromAtomId: "C1", toAtomId: "H3", order: 1 },
        { fromAtomId: "C1", toAtomId: "H4", order: 1 },
      ],
    },
    applications: "Primary component of natural gas, clean hydrocarbon energy source, synthesis gas feedstock.",
    safety: "Extremely flammable gas, potent greenhouse gas (30x more potent than CO₂ over 100 years).",
    relatedElements: [1, 6],
  },
  {
    slug: "boron-trifluoride",
    name: "Boron Trifluoride",
    iupacName: "Trifluoroborane",
    formula: "BF₃",
    category: "vsepr-essential",
    categoryLabel: "VSEPR Geometry",
    description: "An electron-deficient trigonal planar molecule with an incomplete octet on boron (6 valence electrons). The three 120° B–F bonds cancel out, leaving zero net dipole moment.",
    molarMass: 67.81,
    standardState: "gas",
    meltingPoint: 146.3,
    boilingPoint: 173.3,
    density: "2.99 kg/m³",
    vsepr: {
      axeNotation: "AX₃",
      stericNumber: 3,
      bondingPairs: 3,
      lonePairs: 0,
      electronGeometry: "Trigonal Planar",
      molecularGeometry: "Trigonal Planar",
      idealBondAngle: "120°",
      predictedBondAngle: "120°",
      hybridization: "sp²",
      polarity: "Non-polar",
      dipoleMomentDebye: 0.0,
      dipoleVector: [0, 0, 0],
    },
    atoms: [
      { id: "B1", symbol: "B", atomicNumber: 5, position: [0, 0, 0], isCentral: true },
      { id: "F1", symbol: "F", atomicNumber: 9, position: [0, 1.31, 0] },
      { id: "F2", symbol: "F", atomicNumber: 9, position: [1.13, -0.655, 0] },
      { id: "F3", symbol: "F", atomicNumber: 9, position: [-1.13, -0.655, 0] },
    ],
    bonds: [
      { from: "B1", to: "F1", order: 1 },
      { from: "B1", to: "F2", order: 1 },
      { from: "B1", to: "F3", order: 1 },
    ],
    lonePairs: [],
    lewis: {
      atoms: [
        { atomId: "B1", symbol: "B", x: 100, y: 80, lonePairAngles: [] },
        { atomId: "F1", symbol: "F", x: 100, y: 30, lonePairAngles: [0, 90, 180] },
        { atomId: "F2", symbol: "F", x: 145, y: 110, lonePairAngles: [0, 270, 180] },
        { atomId: "F3", symbol: "F", x: 55, y: 110, lonePairAngles: [180, 270, 0] },
      ],
      bonds: [
        { fromAtomId: "B1", toAtomId: "F1", order: 1 },
        { fromAtomId: "B1", toAtomId: "F2", order: 1 },
        { fromAtomId: "B1", toAtomId: "F3", order: 1 },
      ],
    },
    applications: "Powerful Lewis acid catalyst in organic synthesis (e.g. Friedel-Crafts alkylations and polymerizations).",
    safety: "Toxic and corrosive gas; forms hydrofluoric acid upon contact with moisture.",
    relatedElements: [5, 9],
  },
  {
    slug: "sulfur-dioxide",
    name: "Sulfur Dioxide",
    iupacName: "Sulfur dioxide",
    formula: "SO₂",
    category: "vsepr-essential",
    categoryLabel: "VSEPR Geometry",
    description: "A bent molecule derived from a trigonal planar electron geometry (steric number 3). One lone pair pushes the O–S–O bond angle down from 120° to 118.5°, creating a polar molecule.",
    molarMass: 64.066,
    standardState: "gas",
    meltingPoint: 200.75,
    boilingPoint: 263.13,
    density: "2.63 kg/m³",
    vsepr: {
      axeNotation: "AX₂E",
      stericNumber: 3,
      bondingPairs: 2,
      lonePairs: 1,
      electronGeometry: "Trigonal Planar",
      molecularGeometry: "Bent (120°)",
      idealBondAngle: "120°",
      predictedBondAngle: "118.5°",
      hybridization: "sp²",
      polarity: "Polar",
      dipoleMomentDebye: 1.63,
      dipoleVector: [0, -1, 0],
    },
    atoms: [
      { id: "S1", symbol: "S", atomicNumber: 16, position: [0, 0.28, 0], isCentral: true },
      { id: "O1", symbol: "O", atomicNumber: 8, position: [1.25, -0.42, 0] },
      { id: "O2", symbol: "O", atomicNumber: 8, position: [-1.25, -0.42, 0] },
    ],
    bonds: [
      { from: "S1", to: "O1", order: 2 },
      { from: "S1", to: "O2", order: 2 },
    ],
    lonePairs: [
      { id: "LP1", centralAtomId: "S1", position: [0, 1.05, 0] },
    ],
    lewis: {
      atoms: [
        { atomId: "S1", symbol: "S", x: 100, y: 75, lonePairAngles: [90] },
        { atomId: "O1", symbol: "O", x: 155, y: 105, lonePairAngles: [0, 270] },
        { atomId: "O2", symbol: "O", x: 45, y: 105, lonePairAngles: [180, 270] },
      ],
      bonds: [
        { fromAtomId: "S1", toAtomId: "O1", order: 2 },
        { fromAtomId: "S1", toAtomId: "O2", order: 2 },
      ],
    },
    applications: "Food and wine preservative (antioxidant & antimicrobial), sulfuric acid manufacture precursor, bleach in paper milling.",
    safety: "Choking suffocating gas; reacts with atmospheric moisture to form acid rain.",
    relatedElements: [8, 16],
  },
  {
    slug: "phosphorus-pentachloride",
    name: "Phosphorus Pentachloride",
    iupacName: "Pentachloro-λ⁵-phosphane",
    formula: "PCl₅",
    category: "vsepr-essential",
    categoryLabel: "VSEPR Geometry",
    description: "Expanded octet molecule with 10 valence electrons around phosphorus. Forms a trigonal bipyramidal geometry with 2 axial bonds (180° apart) and 3 equatorial bonds (120° apart).",
    molarMass: 208.24,
    standardState: "solid",
    meltingPoint: 433.0,
    boilingPoint: 433.0,
    density: "2.12 g/cm³",
    vsepr: {
      axeNotation: "AX₅",
      stericNumber: 5,
      bondingPairs: 5,
      lonePairs: 0,
      electronGeometry: "Trigonal Bipyramidal",
      molecularGeometry: "Trigonal Bipyramidal",
      idealBondAngle: "90° & 120°",
      predictedBondAngle: "90° & 120°",
      hybridization: "sp³d",
      polarity: "Non-polar",
      dipoleMomentDebye: 0.0,
      dipoleVector: [0, 0, 0],
    },
    atoms: [
      { id: "P1", symbol: "P", atomicNumber: 15, position: [0, 0, 0], isCentral: true },
      { id: "Cl1", symbol: "Cl", atomicNumber: 17, position: [0, 2.02, 0] },
      { id: "Cl2", symbol: "Cl", atomicNumber: 17, position: [0, -2.02, 0] },
      { id: "Cl3", symbol: "Cl", atomicNumber: 17, position: [1.95, 0, 0] },
      { id: "Cl4", symbol: "Cl", atomicNumber: 17, position: [-0.975, 0, 1.69] },
      { id: "Cl5", symbol: "Cl", atomicNumber: 17, position: [-0.975, 0, -1.69] },
    ],
    bonds: [
      { from: "P1", to: "Cl1", order: 1 },
      { from: "P1", to: "Cl2", order: 1 },
      { from: "P1", to: "Cl3", order: 1 },
      { from: "P1", to: "Cl4", order: 1 },
      { from: "P1", to: "Cl5", order: 1 },
    ],
    lonePairs: [],
    lewis: {
      atoms: [
        { atomId: "P1", symbol: "P", x: 100, y: 80, lonePairAngles: [] },
        { atomId: "Cl1", symbol: "Cl", x: 100, y: 30, lonePairAngles: [0, 90, 180] },
        { atomId: "Cl2", symbol: "Cl", x: 100, y: 130, lonePairAngles: [0, 270, 180] },
        { atomId: "Cl3", symbol: "Cl", x: 150, y: 80, lonePairAngles: [0, 90, 270] },
        { atomId: "Cl4", symbol: "Cl", x: 60, y: 60, lonePairAngles: [90, 180, 270] },
        { atomId: "Cl5", symbol: "Cl", x: 60, y: 100, lonePairAngles: [90, 180, 270] },
      ],
      bonds: [
        { fromAtomId: "P1", toAtomId: "Cl1", order: 1 },
        { fromAtomId: "P1", toAtomId: "Cl2", order: 1 },
        { fromAtomId: "P1", toAtomId: "Cl3", order: 1 },
        { fromAtomId: "P1", toAtomId: "Cl4", order: 1 },
        { fromAtomId: "P1", toAtomId: "Cl5", order: 1 },
      ],
    },
    applications: "Chlorinating agent in organic synthesis, electrolyte additive in lithium-ion batteries.",
    safety: "Violently hydrolyzes in water producing hydrochloric acid and phosphoric acid fumes.",
    relatedElements: [15, 17],
  },
  {
    slug: "sulfur-hexafluoride",
    name: "Sulfur Hexafluoride",
    iupacName: "Hexafluoro-λ⁶-sulfane",
    formula: "SF₆",
    category: "vsepr-essential",
    categoryLabel: "VSEPR Geometry",
    description: "Hypervalent octahedral molecule with 12 valence electrons on sulfur. Six identical S–F bonds form perfect 90° angles with complete inversion symmetry, making it non-polar and exceptionally stable.",
    molarMass: 146.06,
    standardState: "gas",
    meltingPoint: 222.35,
    boilingPoint: 209.35, // sublimation
    density: "6.13 kg/m³",
    vsepr: {
      axeNotation: "AX₆",
      stericNumber: 6,
      bondingPairs: 6,
      lonePairs: 0,
      electronGeometry: "Octahedral",
      molecularGeometry: "Octahedral",
      idealBondAngle: "90°",
      predictedBondAngle: "90°",
      hybridization: "sp³d²",
      polarity: "Non-polar",
      dipoleMomentDebye: 0.0,
      dipoleVector: [0, 0, 0],
    },
    atoms: [
      { id: "S1", symbol: "S", atomicNumber: 16, position: [0, 0, 0], isCentral: true },
      { id: "F1", symbol: "F", atomicNumber: 9, position: [1.56, 0, 0] },
      { id: "F2", symbol: "F", atomicNumber: 9, position: [-1.56, 0, 0] },
      { id: "F3", symbol: "F", atomicNumber: 9, position: [0, 1.56, 0] },
      { id: "F4", symbol: "F", atomicNumber: 9, position: [0, -1.56, 0] },
      { id: "F5", symbol: "F", atomicNumber: 9, position: [0, 0, 1.56] },
      { id: "F6", symbol: "F", atomicNumber: 9, position: [0, 0, -1.56] },
    ],
    bonds: [
      { from: "S1", to: "F1", order: 1 },
      { from: "S1", to: "F2", order: 1 },
      { from: "S1", to: "F3", order: 1 },
      { from: "S1", to: "F4", order: 1 },
      { from: "S1", to: "F5", order: 1 },
      { from: "S1", to: "F6", order: 1 },
    ],
    lonePairs: [],
    lewis: {
      atoms: [
        { atomId: "S1", symbol: "S", x: 100, y: 80, lonePairAngles: [] },
        { atomId: "F1", symbol: "F", x: 150, y: 80, lonePairAngles: [0, 90, 270] },
        { atomId: "F2", symbol: "F", x: 50, y: 80, lonePairAngles: [180, 90, 270] },
        { atomId: "F3", symbol: "F", x: 100, y: 30, lonePairAngles: [90, 0, 180] },
        { atomId: "F4", symbol: "F", x: 100, y: 130, lonePairAngles: [270, 0, 180] },
        { atomId: "F5", symbol: "F", x: 135, y: 45, lonePairAngles: [45, 135, 315] },
        { atomId: "F6", symbol: "F", x: 65, y: 115, lonePairAngles: [135, 225, 45] },
      ],
      bonds: [
        { fromAtomId: "S1", toAtomId: "F1", order: 1 },
        { fromAtomId: "S1", toAtomId: "F2", order: 1 },
        { fromAtomId: "S1", toAtomId: "F3", order: 1 },
        { fromAtomId: "S1", toAtomId: "F4", order: 1 },
        { fromAtomId: "S1", toAtomId: "F5", order: 1 },
        { fromAtomId: "S1", toAtomId: "F6", order: 1 },
      ],
    },
    applications: "High-voltage electrical insulator in circuit breakers and switchgear; medical retinal surgery tamponade.",
    safety: "Extremely potent greenhouse gas (23,500x more potent than CO₂). Non-toxic and chemically inert.",
    relatedElements: [9, 16],
  },
  {
    slug: "xenon-tetrafluoride",
    name: "Xenon Tetrafluoride",
    iupacName: "Tetrafluoro-λ⁴-xenane",
    formula: "XeF₄",
    category: "vsepr-essential",
    categoryLabel: "VSEPR Geometry",
    description: "Historic noble gas compound. With 4 bonding pairs and 2 lone pairs (steric number 6), the two lone pairs occupy opposite axial positions to minimize repulsion, yielding a planar square geometry with zero net dipole.",
    molarMass: 207.28,
    standardState: "solid",
    meltingPoint: 390.25,
    boilingPoint: 388.0,
    density: "4.04 g/cm³",
    vsepr: {
      axeNotation: "AX₄E₂",
      stericNumber: 6,
      bondingPairs: 4,
      lonePairs: 2,
      electronGeometry: "Octahedral",
      molecularGeometry: "Square Planar",
      idealBondAngle: "90°",
      predictedBondAngle: "90°",
      hybridization: "sp³d²",
      polarity: "Non-polar",
      dipoleMomentDebye: 0.0,
      dipoleVector: [0, 0, 0],
    },
    atoms: [
      { id: "Xe1", symbol: "Xe", atomicNumber: 54, position: [0, 0, 0], isCentral: true },
      { id: "F1", symbol: "F", atomicNumber: 9, position: [1.95, 0, 0] },
      { id: "F2", symbol: "F", atomicNumber: 9, position: [-1.95, 0, 0] },
      { id: "F3", symbol: "F", atomicNumber: 9, position: [0, 0, 1.95] },
      { id: "F4", symbol: "F", atomicNumber: 9, position: [0, 0, -1.95] },
    ],
    bonds: [
      { from: "Xe1", to: "F1", order: 1 },
      { from: "Xe1", to: "F2", order: 1 },
      { from: "Xe1", to: "F3", order: 1 },
      { from: "Xe1", to: "F4", order: 1 },
    ],
    lonePairs: [
      { id: "LP1", centralAtomId: "Xe1", position: [0, 1.25, 0] },
      { id: "LP2", centralAtomId: "Xe1", position: [0, -1.25, 0] },
    ],
    lewis: {
      atoms: [
        { atomId: "Xe1", symbol: "Xe", x: 100, y: 80, lonePairAngles: [90, 270] },
        { atomId: "F1", symbol: "F", x: 150, y: 80, lonePairAngles: [0, 90, 270] },
        { atomId: "F2", symbol: "F", x: 50, y: 80, lonePairAngles: [180, 90, 270] },
        { atomId: "F3", symbol: "F", x: 100, y: 35, lonePairAngles: [90, 0, 180] },
        { atomId: "F4", symbol: "F", x: 100, y: 125, lonePairAngles: [270, 0, 180] },
      ],
      bonds: [
        { fromAtomId: "Xe1", toAtomId: "F1", order: 1 },
        { fromAtomId: "Xe1", toAtomId: "F2", order: 1 },
        { fromAtomId: "Xe1", toAtomId: "F3", order: 1 },
        { fromAtomId: "Xe1", toAtomId: "F4", order: 1 },
      ],
    },
    applications: "Disproved the dogma that noble gases are completely chemically inert; used as a selective fluorinating agent.",
    safety: "Reacts vigorously with water to produce explosive xenon trioxide (XeO₃).",
    relatedElements: [9, 54],
  },
  {
    slug: "sulfur-tetrafluoride",
    name: "Sulfur Tetrafluoride",
    iupacName: "Tetrafluoro-λ⁴-sulfane",
    formula: "SF₄",
    category: "vsepr-essential",
    categoryLabel: "VSEPR Geometry",
    description: "Features a seesaw molecular geometry ($AX_4E$). The single equatorial lone pair pushes axial F–S–F bonds to 173° and equatorial F–S–F bonds to 101.6°, yielding a significant net dipole.",
    molarMass: 108.06,
    standardState: "gas",
    meltingPoint: 152.15,
    boilingPoint: 235.15,
    density: "4.5 kg/m³",
    vsepr: {
      axeNotation: "AX₄E",
      stericNumber: 5,
      bondingPairs: 4,
      lonePairs: 1,
      electronGeometry: "Trigonal Bipyramidal",
      molecularGeometry: "Seesaw",
      idealBondAngle: "90° & 120°",
      predictedBondAngle: "87° & 102°",
      hybridization: "sp³d",
      polarity: "Polar",
      dipoleMomentDebye: 0.63,
      dipoleVector: [-1, 0, 0],
    },
    atoms: [
      { id: "S1", symbol: "S", atomicNumber: 16, position: [0, 0, 0], isCentral: true },
      { id: "F1", symbol: "F", atomicNumber: 9, position: [0, 1.64, 0] },
      { id: "F2", symbol: "F", atomicNumber: 9, position: [0, -1.64, 0] },
      { id: "F3", symbol: "F", atomicNumber: 9, position: [-1.22, 0, 0.98] },
      { id: "F4", symbol: "F", atomicNumber: 9, position: [-1.22, 0, -0.98] },
    ],
    bonds: [
      { from: "S1", to: "F1", order: 1 },
      { from: "S1", to: "F2", order: 1 },
      { from: "S1", to: "F3", order: 1 },
      { from: "S1", to: "F4", order: 1 },
    ],
    lonePairs: [
      { id: "LP1", centralAtomId: "S1", position: [1.1, 0, 0] },
    ],
    lewis: {
      atoms: [
        { atomId: "S1", symbol: "S", x: 100, y: 80, lonePairAngles: [0] },
        { atomId: "F1", symbol: "F", x: 100, y: 30, lonePairAngles: [0, 90, 180] },
        { atomId: "F2", symbol: "F", x: 100, y: 130, lonePairAngles: [0, 270, 180] },
        { atomId: "F3", symbol: "F", x: 50, y: 55, lonePairAngles: [90, 180, 270] },
        { atomId: "F4", symbol: "F", x: 50, y: 105, lonePairAngles: [90, 180, 270] },
      ],
      bonds: [
        { fromAtomId: "S1", toAtomId: "F1", order: 1 },
        { fromAtomId: "S1", toAtomId: "F2", order: 1 },
        { fromAtomId: "S1", toAtomId: "F3", order: 1 },
        { fromAtomId: "S1", toAtomId: "F4", order: 1 },
      ],
    },
    applications: "Specialized fluorination reagent to convert C=O and P=O groups to CF₂ and PF₂ derivatives.",
    safety: "Highly toxic gas; releases corrosive HF when exposed to humidity.",
    relatedElements: [9, 16],
  },
  {
    slug: "ozone",
    name: "Ozone",
    iupacName: "Trioxygen",
    formula: "O₃",
    category: "atmospheric",
    categoryLabel: "Atmospheric gas",
    description: "An allotrope of oxygen featuring resonance-delocalized bonding. The central oxygen atom has one lone pair ($AX_2E$), giving it a bent shape (116.8°) and distinct polarity.",
    molarMass: 47.998,
    standardState: "gas",
    meltingPoint: 80.7,
    boilingPoint: 161.3,
    density: "2.14 kg/m³",
    vsepr: {
      axeNotation: "AX₂E",
      stericNumber: 3,
      bondingPairs: 2,
      lonePairs: 1,
      electronGeometry: "Trigonal Planar",
      molecularGeometry: "Bent (120°)",
      idealBondAngle: "120°",
      predictedBondAngle: "116.8°",
      hybridization: "sp²",
      polarity: "Polar",
      dipoleMomentDebye: 0.53,
      dipoleVector: [0, -1, 0],
    },
    atoms: [
      { id: "O1", symbol: "O", atomicNumber: 8, position: [0, 0.22, 0], isCentral: true },
      { id: "O2", symbol: "O", atomicNumber: 8, position: [1.08, -0.34, 0] },
      { id: "O3", symbol: "O", atomicNumber: 8, position: [-1.08, -0.34, 0] },
    ],
    bonds: [
      { from: "O1", to: "O2", order: 2 },
      { from: "O1", to: "O3", order: 1 },
    ],
    lonePairs: [
      { id: "LP1", centralAtomId: "O1", position: [0, 0.95, 0] },
    ],
    lewis: {
      atoms: [
        { atomId: "O1", symbol: "O", x: 100, y: 75, lonePairAngles: [90] },
        { atomId: "O2", symbol: "O", x: 155, y: 105, lonePairAngles: [0, 270] },
        { atomId: "O3", symbol: "O", x: 45, y: 105, lonePairAngles: [180, 270, 90] },
      ],
      bonds: [
        { fromAtomId: "O1", toAtomId: "O2", order: 2 },
        { fromAtomId: "O1", toAtomId: "O3", order: 1 },
      ],
    },
    applications: "Stratospheric UV shield protecting Earth's biosphere; industrial water disinfection and odor removal.",
    safety: "Strong respiratory irritant and powerful oxidizer at ground level.",
    relatedElements: [8],
  },
  {
    slug: "ethene",
    name: "Ethene (Ethylene)",
    iupacName: "Ethene",
    formula: "C₂H₄",
    category: "organic",
    categoryLabel: "Organic compound",
    description: "The simplest alkene containing a planar carbon–carbon double bond ($\sigma + \pi$). Both carbons are $sp^2$ hybridized with 120° bond angles.",
    molarMass: 28.054,
    standardState: "gas",
    meltingPoint: 104.0,
    boilingPoint: 169.2,
    density: "1.18 kg/m³",
    vsepr: {
      axeNotation: "AX₃ (each C)",
      stericNumber: 3,
      bondingPairs: 3,
      lonePairs: 0,
      electronGeometry: "Trigonal Planar",
      molecularGeometry: "Trigonal Planar",
      idealBondAngle: "120°",
      predictedBondAngle: "121.3°",
      hybridization: "sp²",
      polarity: "Non-polar",
      dipoleMomentDebye: 0.0,
      dipoleVector: [0, 0, 0],
    },
    atoms: [
      { id: "C1", symbol: "C", atomicNumber: 6, position: [0.67, 0, 0], isCentral: true },
      { id: "C2", symbol: "C", atomicNumber: 6, position: [-0.67, 0, 0], isCentral: true },
      { id: "H1", symbol: "H", atomicNumber: 1, position: [1.23, 0.93, 0] },
      { id: "H2", symbol: "H", atomicNumber: 1, position: [1.23, -0.93, 0] },
      { id: "H3", symbol: "H", atomicNumber: 1, position: [-1.23, 0.93, 0] },
      { id: "H4", symbol: "H", atomicNumber: 1, position: [-1.23, -0.93, 0] },
    ],
    bonds: [
      { from: "C1", to: "C2", order: 2 },
      { from: "C1", to: "H1", order: 1 },
      { from: "C1", to: "H2", order: 1 },
      { from: "C2", to: "H3", order: 1 },
      { from: "C2", to: "H4", order: 1 },
    ],
    lonePairs: [],
    lewis: {
      atoms: [
        { atomId: "C1", symbol: "C", x: 120, y: 80, lonePairAngles: [] },
        { atomId: "C2", symbol: "C", x: 80, y: 80, lonePairAngles: [] },
        { atomId: "H1", symbol: "H", x: 155, y: 50, lonePairAngles: [] },
        { atomId: "H2", symbol: "H", x: 155, y: 110, lonePairAngles: [] },
        { atomId: "H3", symbol: "H", x: 45, y: 50, lonePairAngles: [] },
        { atomId: "H4", symbol: "H", x: 45, y: 110, lonePairAngles: [] },
      ],
      bonds: [
        { fromAtomId: "C1", toAtomId: "C2", order: 2 },
        { fromAtomId: "C1", toAtomId: "H1", order: 1 },
        { fromAtomId: "C1", toAtomId: "H2", order: 1 },
        { fromAtomId: "C2", toAtomId: "H3", order: 1 },
        { fromAtomId: "C2", toAtomId: "H4", order: 1 },
      ],
    },
    applications: "Most manufactured organic compound in the world; essential precursor to polyethylene plastics and plant fruit-ripening hormone.",
    safety: "Extremely flammable hydrocarbon gas.",
    relatedElements: [1, 6],
  },
  {
    slug: "ethanol",
    name: "Ethanol",
    iupacName: "Ethanol",
    formula: "C₂H₅OH",
    category: "organic",
    categoryLabel: "Organic compound",
    description: "Two-carbon alcohol containing a polar hydroxyl (–OH) group. Capable of extensive hydrogen bonding, giving it a relatively high boiling point (78.2°C) and water miscibility.",
    molarMass: 46.069,
    standardState: "liquid",
    meltingPoint: 159.05,
    boilingPoint: 351.38,
    density: "0.789 g/cm³",
    vsepr: {
      axeNotation: "AX₄ (C) / AX₂E₂ (O)",
      stericNumber: 4,
      bondingPairs: 4,
      lonePairs: 0,
      electronGeometry: "Tetrahedral",
      molecularGeometry: "Tetrahedral",
      idealBondAngle: "109.5°",
      predictedBondAngle: "109.5° & 104.5°",
      hybridization: "sp³",
      polarity: "Polar",
      dipoleMomentDebye: 1.69,
      dipoleVector: [0.8, -0.6, 0],
    },
    atoms: [
      { id: "C1", symbol: "C", atomicNumber: 6, position: [-1.2, 0, 0] },
      { id: "C2", symbol: "C", atomicNumber: 6, position: [0.2, 0.4, 0] },
      { id: "O1", symbol: "O", atomicNumber: 8, position: [1.1, -0.6, 0] },
      { id: "H1", symbol: "H", atomicNumber: 1, position: [-1.4, -0.6, 0.8] },
      { id: "H2", symbol: "H", atomicNumber: 1, position: [-1.4, -0.6, -0.8] },
      { id: "H3", symbol: "H", atomicNumber: 1, position: [-1.8, 0.8, 0] },
      { id: "H4", symbol: "H", atomicNumber: 1, position: [0.4, 1.0, 0.8] },
      { id: "H5", symbol: "H", atomicNumber: 1, position: [0.4, 1.0, -0.8] },
      { id: "H6", symbol: "H", atomicNumber: 1, position: [2.0, -0.4, 0] },
    ],
    bonds: [
      { from: "C1", to: "C2", order: 1 },
      { from: "C2", to: "O1", order: 1 },
      { from: "O1", to: "H6", order: 1 },
      { from: "C1", to: "H1", order: 1 },
      { from: "C1", to: "H2", order: 1 },
      { from: "C1", to: "H3", order: 1 },
      { from: "C2", to: "H4", order: 1 },
      { from: "C2", to: "H5", order: 1 },
    ],
    lonePairs: [
      { id: "LP1", centralAtomId: "O1", position: [1.1, -1.1, 0.5] },
      { id: "LP2", centralAtomId: "O1", position: [1.1, -1.1, -0.5] },
    ],
    lewis: {
      atoms: [
        { atomId: "C1", symbol: "C", x: 50, y: 80, lonePairAngles: [] },
        { atomId: "C2", symbol: "C", x: 95, y: 80, lonePairAngles: [] },
        { atomId: "O1", symbol: "O", x: 140, y: 80, lonePairAngles: [90, 270] },
        { atomId: "H6", symbol: "H", x: 175, y: 80, lonePairAngles: [] },
        { atomId: "H1", symbol: "H", x: 50, y: 40, lonePairAngles: [] },
        { atomId: "H2", symbol: "H", x: 50, y: 120, lonePairAngles: [] },
        { atomId: "H3", symbol: "H", x: 20, y: 80, lonePairAngles: [] },
        { atomId: "H4", symbol: "H", x: 95, y: 40, lonePairAngles: [] },
        { atomId: "H5", symbol: "H", x: 95, y: 120, lonePairAngles: [] },
      ],
      bonds: [
        { fromAtomId: "C1", toAtomId: "C2", order: 1 },
        { fromAtomId: "C2", toAtomId: "O1", order: 1 },
        { fromAtomId: "O1", toAtomId: "H6", order: 1 },
        { fromAtomId: "C1", toAtomId: "H1", order: 1 },
        { fromAtomId: "C1", toAtomId: "H2", order: 1 },
        { fromAtomId: "C1", toAtomId: "H3", order: 1 },
        { fromAtomId: "C2", toAtomId: "H4", order: 1 },
        { fromAtomId: "C2", toAtomId: "H5", order: 1 },
      ],
    },
    applications: "Renewable biofuel additive, antiseptic disinfectant, laboratory solvent, alcoholic beverages.",
    safety: "Flammable liquid and vapor. Central nervous system depressant in excessive biological exposure.",
    relatedElements: [1, 6, 8],
  },
  {
    slug: "benzene",
    name: "Benzene",
    iupacName: "Benzene",
    formula: "C₆H₆",
    category: "organic",
    categoryLabel: "Organic compound",
    description: "The archetype aromatic hydrocarbon. Six $sp^2$ hybridized carbons form a perfectly planar hexagon with a continuous delocalized $\\pi$-electron cloud (Hückel's $4n+2$ rule with $6\\pi$ electrons).",
    molarMass: 78.114,
    standardState: "liquid",
    meltingPoint: 278.68,
    boilingPoint: 353.24,
    density: "0.876 g/cm³",
    vsepr: {
      axeNotation: "AX₃ (all carbons)",
      stericNumber: 3,
      bondingPairs: 3,
      lonePairs: 0,
      electronGeometry: "Trigonal Planar",
      molecularGeometry: "Trigonal Planar",
      idealBondAngle: "120°",
      predictedBondAngle: "120°",
      hybridization: "sp²",
      polarity: "Non-polar",
      dipoleMomentDebye: 0.0,
      dipoleVector: [0, 0, 0],
    },
    atoms: [
      { id: "C1", symbol: "C", atomicNumber: 6, position: [1.4, 0, 0] },
      { id: "C2", symbol: "C", atomicNumber: 6, position: [0.7, 1.21, 0] },
      { id: "C3", symbol: "C", atomicNumber: 6, position: [-0.7, 1.21, 0] },
      { id: "C4", symbol: "C", atomicNumber: 6, position: [-1.4, 0, 0] },
      { id: "C5", symbol: "C", atomicNumber: 6, position: [-0.7, -1.21, 0] },
      { id: "C6", symbol: "C", atomicNumber: 6, position: [0.7, -1.21, 0] },
      { id: "H1", symbol: "H", atomicNumber: 1, position: [2.48, 0, 0] },
      { id: "H2", symbol: "H", atomicNumber: 1, position: [1.24, 2.15, 0] },
      { id: "H3", symbol: "H", atomicNumber: 1, position: [-1.24, 2.15, 0] },
      { id: "H4", symbol: "H", atomicNumber: 1, position: [-2.48, 0, 0] },
      { id: "H5", symbol: "H", atomicNumber: 1, position: [-1.24, -2.15, 0] },
      { id: "H6", symbol: "H", atomicNumber: 1, position: [1.24, -2.15, 0] },
    ],
    bonds: [
      { from: "C1", to: "C2", order: 2 },
      { from: "C2", to: "C3", order: 1 },
      { from: "C3", to: "C4", order: 2 },
      { from: "C4", to: "C5", order: 1 },
      { from: "C5", to: "C6", order: 2 },
      { from: "C6", to: "C1", order: 1 },
      { from: "C1", to: "H1", order: 1 },
      { from: "C2", to: "H2", order: 1 },
      { from: "C3", to: "H3", order: 1 },
      { from: "C4", to: "H4", order: 1 },
      { from: "C5", to: "H5", order: 1 },
      { from: "C6", to: "H6", order: 1 },
    ],
    lonePairs: [],
    lewis: {
      atoms: [
        { atomId: "C1", symbol: "C", x: 135, y: 80, lonePairAngles: [] },
        { atomId: "C2", symbol: "C", x: 118, y: 48, lonePairAngles: [] },
        { atomId: "C3", symbol: "C", x: 82, y: 48, lonePairAngles: [] },
        { atomId: "C4", symbol: "C", x: 65, y: 80, lonePairAngles: [] },
        { atomId: "C5", symbol: "C", x: 82, y: 112, lonePairAngles: [] },
        { atomId: "C6", symbol: "C", x: 118, y: 112, lonePairAngles: [] },
        { atomId: "H1", symbol: "H", x: 165, y: 80, lonePairAngles: [] },
        { atomId: "H2", symbol: "H", x: 135, y: 22, lonePairAngles: [] },
        { atomId: "H3", symbol: "H", x: 65, y: 22, lonePairAngles: [] },
        { atomId: "H4", symbol: "H", x: 35, y: 80, lonePairAngles: [] },
        { atomId: "H5", symbol: "H", x: 65, y: 138, lonePairAngles: [] },
        { atomId: "H6", symbol: "H", x: 135, y: 138, lonePairAngles: [] },
      ],
      bonds: [
        { fromAtomId: "C1", toAtomId: "C2", order: 2 },
        { fromAtomId: "C2", toAtomId: "C3", order: 1 },
        { fromAtomId: "C3", toAtomId: "C4", order: 2 },
        { fromAtomId: "C4", toAtomId: "C5", order: 1 },
        { fromAtomId: "C5", toAtomId: "C6", order: 2 },
        { fromAtomId: "C6", toAtomId: "C1", order: 1 },
        { fromAtomId: "C1", toAtomId: "H1", order: 1 },
        { fromAtomId: "C2", toAtomId: "H2", order: 1 },
        { fromAtomId: "C3", toAtomId: "H3", order: 1 },
        { fromAtomId: "C4", toAtomId: "H4", order: 1 },
        { fromAtomId: "C5", toAtomId: "H5", order: 1 },
        { fromAtomId: "C6", toAtomId: "H6", order: 1 },
      ],
    },
    applications: "Foundational building block for pharmaceuticals, synthetic rubber, polymers (polystyrene, nylon), and dyes.",
    safety: "Volatile, highly flammable, and a known human carcinogen.",
    relatedElements: [1, 6],
  },
  {
    slug: "glucose",
    name: "D-Glucose",
    iupacName: "(2R,3S,4R,5R)-2,3,4,5,6-Pentahydroxyhexanal",
    formula: "C₆H₁₂O₆",
    category: "biomolecule",
    categoryLabel: "Biomolecule",
    description: "The primary monosaccharide and fundamental energy fuel in biology. Converted by cellular respiration into ATP to power biological systems.",
    molarMass: 180.156,
    standardState: "solid",
    meltingPoint: 419.15,
    boilingPoint: null,
    density: "1.54 g/cm³",
    vsepr: {
      axeNotation: "AX₄ (C carbons)",
      stericNumber: 4,
      bondingPairs: 4,
      lonePairs: 0,
      electronGeometry: "Tetrahedral",
      molecularGeometry: "Tetrahedral",
      idealBondAngle: "109.5°",
      predictedBondAngle: "109.5°",
      hybridization: "sp³",
      polarity: "Polar",
      dipoleMomentDebye: 2.8,
      dipoleVector: [0.3, 0.6, -0.4],
    },
    atoms: [
      { id: "C1", symbol: "C", atomicNumber: 6, position: [-1.4, 0.4, 0] },
      { id: "C2", symbol: "C", atomicNumber: 6, position: [-0.6, -0.8, 0.3] },
      { id: "C3", symbol: "C", atomicNumber: 6, position: [0.8, -0.6, -0.2] },
      { id: "C4", symbol: "C", atomicNumber: 6, position: [1.4, 0.6, 0.4] },
      { id: "C5", symbol: "C", atomicNumber: 6, position: [0.5, 1.7, -0.1] },
      { id: "O5", symbol: "O", atomicNumber: 8, position: [-0.8, 1.4, 0.2] },
      { id: "C6", symbol: "C", atomicNumber: 6, position: [1.1, 3.0, 0.2] },
      { id: "O1", symbol: "O", atomicNumber: 8, position: [-2.6, 0.4, -0.6] },
      { id: "O2", symbol: "O", atomicNumber: 8, position: [-0.9, -1.9, -0.5] },
      { id: "O3", symbol: "O", atomicNumber: 8, position: [1.5, -1.7, 0.3] },
      { id: "O4", symbol: "O", atomicNumber: 8, position: [2.7, 0.4, -0.1] },
      { id: "O6", symbol: "O", atomicNumber: 8, position: [2.3, 3.1, -0.4] },
      { id: "H1", symbol: "H", atomicNumber: 1, position: [-1.5, 0.4, 1.0] },
      { id: "H2", symbol: "H", atomicNumber: 1, position: [-0.6, -0.9, 1.3] },
      { id: "H3", symbol: "H", atomicNumber: 1, position: [0.8, -0.6, -1.2] },
      { id: "H4", symbol: "H", atomicNumber: 1, position: [1.4, 0.6, 1.4] },
      { id: "H5", symbol: "H", atomicNumber: 1, position: [0.3, 1.7, -1.1] },
    ],
    bonds: [
      { from: "C1", to: "C2", order: 1 },
      { from: "C2", to: "C3", order: 1 },
      { from: "C3", to: "C4", order: 1 },
      { from: "C4", to: "C5", order: 1 },
      { from: "C5", to: "O5", order: 1 },
      { from: "O5", to: "C1", order: 1 },
      { from: "C5", to: "C6", order: 1 },
      { from: "C1", to: "O1", order: 1 },
      { from: "C2", to: "O2", order: 1 },
      { from: "C3", to: "O3", order: 1 },
      { from: "C4", to: "O4", order: 1 },
      { from: "C6", to: "O6", order: 1 },
      { from: "C1", to: "H1", order: 1 },
      { from: "C2", to: "H2", order: 1 },
      { from: "C3", to: "H3", order: 1 },
      { from: "C4", to: "H4", order: 1 },
      { from: "C5", to: "H5", order: 1 },
    ],
    lonePairs: [],
    lewis: {
      atoms: [
        { atomId: "C1", symbol: "C", x: 60, y: 70, lonePairAngles: [] },
        { atomId: "C2", symbol: "C", x: 80, y: 110, lonePairAngles: [] },
        { atomId: "C3", symbol: "C", x: 120, y: 110, lonePairAngles: [] },
        { atomId: "C4", symbol: "C", x: 140, y: 70, lonePairAngles: [] },
        { atomId: "C5", symbol: "C", x: 120, y: 40, lonePairAngles: [] },
        { atomId: "O5", symbol: "O", x: 80, y: 40, lonePairAngles: [90, 270] },
      ],
      bonds: [
        { fromAtomId: "C1", toAtomId: "C2", order: 1 },
        { fromAtomId: "C2", toAtomId: "C3", order: 1 },
        { fromAtomId: "C3", toAtomId: "C4", order: 1 },
        { fromAtomId: "C4", toAtomId: "C5", order: 1 },
        { fromAtomId: "C5", toAtomId: "O5", order: 1 },
        { fromAtomId: "O5", toAtomId: "C1", order: 1 },
      ],
    },
    applications: "Primary metabolic substrate for cellular energy production, precursor to glycogen and cellulose, medical IV rehydration.",
    safety: "Essential dietary nutrient; chronic excessive consumption implicated in metabolic disorders.",
    relatedElements: [1, 6, 8],
  },
];

export const moleculeBySlug = new Map(curatedMolecules.map((m) => [m.slug, m]));

export function resolveMolecule(slug: string | null | undefined): MoleculeRecord {
  if (!slug) return curatedMolecules[0];
  const found = moleculeBySlug.get(slug.toLowerCase().trim());
  return found ?? curatedMolecules[0];
}

/**
 * Builds a dynamic custom MoleculeRecord based on user-configured central atom, ligands, and lone pairs.
 */
export function buildCustomVseprMolecule(
  centralSymbol: string,
  ligands: { symbol: string; bondOrder: 1 | 2 | 3 }[],
  lonePairs: number,
): MoleculeRecord {
  const centralElem = ELEMENT_MAP.get(centralSymbol) ?? elements[5]; // Carbon default
  const bondingPairs = ligands.length;
  const stericNumber = bondingPairs + lonePairs;

  let key = `AX${bondingPairs}`;
  if (lonePairs > 0) key += `E${lonePairs > 1 ? lonePairs : ""}`;

  const fallbackElectronGeom: VseprElectronGeometry =
    stericNumber === 2
      ? "Linear"
      : stericNumber === 3
        ? "Trigonal Planar"
        : stericNumber === 4
          ? "Tetrahedral"
          : stericNumber === 5
            ? "Trigonal Bipyramidal"
            : "Octahedral";

  const fallbackMolecularGeom: VseprMolecularGeometry =
    bondingPairs === 2 && lonePairs === 0
      ? "Linear"
      : bondingPairs === 2 && lonePairs === 2
        ? "Bent (104.5°)"
        : "Tetrahedral";

  const template = VSEPR_TEMPLATES[key] ?? {
    stericNumber,
    bondingPairs,
    lonePairs,
    axeNotation: `AX${bondingPairs}${lonePairs ? `E${lonePairs}` : ""}`,
    electronGeometry: fallbackElectronGeom,
    molecularGeometry: fallbackMolecularGeom,
    idealBondAngle: "109.5°",
    predictedBondAngle: "109.5°",
    hybridization: stericNumber === 2 ? "sp" : stericNumber === 3 ? "sp²" : stericNumber === 4 ? "sp³" : stericNumber === 5 ? "sp³d" : "sp³d²",
    defaultPolarity: lonePairs > 0 ? "Polar" : "Non-polar",
  };

  const { ligandPositions, lonePairPositions } = generateVsepr3DPositions(bondingPairs, lonePairs);

  const atoms: MoleculeAtom[] = [
    {
      id: `${centralSymbol}1`,
      symbol: centralSymbol,
      atomicNumber: centralElem.atomicNumber,
      position: [0, 0, 0],
      isCentral: true,
    },
  ];

  const bonds: MoleculeBond[] = [];
  const related = new Set<number>([centralElem.atomicNumber]);

  ligands.forEach((ligand, i) => {
    const ligElem = ELEMENT_MAP.get(ligand.symbol) ?? elements[0];
    related.add(ligElem.atomicNumber);
    const atomId = `${ligand.symbol}${i + 1}`;
    atoms.push({
      id: atomId,
      symbol: ligand.symbol,
      atomicNumber: ligElem.atomicNumber,
      position: ligandPositions[i] ?? [0, 1.2, 0],
    });
    bonds.push({
      from: `${centralSymbol}1`,
      to: atomId,
      order: ligand.bondOrder,
    });
  });

  const lonePairRecords: LonePairRecord[] = lonePairPositions.map((pos, i) => ({
    id: `LP${i + 1}`,
    centralAtomId: `${centralSymbol}1`,
    position: pos,
  }));

  const netDipole = calculateNetDipole(
    centralSymbol,
    [0, 0, 0],
    atoms.slice(1).map((a) => ({ symbol: a.symbol, position: a.position })),
  );

  // Derive formula string
  const counts: Record<string, number> = { [centralSymbol]: 1 };
  ligands.forEach((l) => {
    counts[l.symbol] = (counts[l.symbol] ?? 0) + 1;
  });
  const formula = Object.entries(counts)
    .map(([s, c]) => `${s}${c > 1 ? String(c).replace(/\d/g, (d) => "₀₁₂₃₄₅₆₇₈₉"[Number(d)]) : ""}`)
    .join("");

  const molarMass = Object.entries(counts).reduce((sum, [sym, count]) => {
    const elem = ELEMENT_MAP.get(sym);
    return sum + (elem ? parseFloat(elem.atomicMass) * count : 12 * count);
  }, 0);

  const lewisAtoms = [
    { atomId: `${centralSymbol}1`, symbol: centralSymbol, x: 100, y: 80, lonePairAngles: Array.from({ length: lonePairs }, (_, i) => 90 * (i + 1)) },
    ...ligands.map((l, i) => {
      const angle = (i * 2 * Math.PI) / Math.max(1, ligands.length);
      return {
        atomId: `${l.symbol}${i + 1}`,
        symbol: l.symbol,
        x: Math.round(100 + Math.cos(angle) * 45),
        y: Math.round(80 + Math.sin(angle) * 45),
        lonePairAngles: [],
      };
    }),
  ];

  return {
    slug: `custom-${centralSymbol.toLowerCase()}-${bondingPairs}-${lonePairs}`,
    name: `Custom ${centralSymbol} Compound (${template.molecularGeometry})`,
    iupacName: `Custom VSEPR ${template.axeNotation}`,
    formula,
    category: "custom",
    categoryLabel: "Custom Sandbox Model",
    description: `Constructed interactive model with ${bondingPairs} bonded atom${bondingPairs > 1 ? "s" : ""} and ${lonePairs} lone pair${lonePairs > 1 ? "s" : ""} on ${centralElem.name}. Exhibits ${template.molecularGeometry.toLowerCase()} geometry with ${template.hybridization} hybridization.`,
    molarMass: Number(molarMass.toFixed(3)),
    standardState: "gas",
    vsepr: {
      axeNotation: template.axeNotation,
      stericNumber: template.stericNumber,
      bondingPairs,
      lonePairs,
      electronGeometry: template.electronGeometry,
      molecularGeometry: template.molecularGeometry,
      idealBondAngle: template.idealBondAngle,
      predictedBondAngle: template.predictedBondAngle,
      hybridization: template.hybridization,
      polarity: netDipole.polarity,
      dipoleMomentDebye: netDipole.dipoleDebye,
      dipoleVector: netDipole.dipoleVector,
    },
    atoms,
    bonds,
    lonePairs: lonePairRecords,
    lewis: {
      atoms: lewisAtoms,
      bonds: bonds.map((b) => ({ fromAtomId: b.from, toAtomId: b.to, order: b.order })),
    },
    applications: "Custom theoretical structure modeled via valence shell electron pair repulsion (VSEPR) theory.",
    safety: "Theoretical teaching model sandbox.",
    relatedElements: Array.from(related),
  };
}

export const VSEPR_QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    id: "vsepr-1",
    prompt: "What is the molecular geometry of a molecule with 2 bonded atoms and 2 lone pairs on the central atom (AX₂E₂), such as water (H₂O)?",
    options: ["Linear", "Bent (~104.5°)", "Trigonal Pyramidal", "Tetrahedral"],
    answer: 1,
    explanation: "Two bonded atoms and two lone pairs yield steric number 4 (tetrahedral electron geometry), but the visible molecular geometry is Bent with an angle around 104.5°.",
  },
  {
    id: "vsepr-2",
    prompt: "Why is carbon dioxide (CO₂) non-polar even though each individual C=O bond is strongly polar?",
    options: [
      "The bond dipoles pull in exact opposite directions (180°) and cancel out",
      "Oxygen is less electronegative than carbon",
      "Carbon dioxide has two lone pairs on carbon",
      "Carbon forms ionic bonds with oxygen",
    ],
    answer: 0,
    explanation: "CO₂ is linear (180°). Both C=O bond dipoles have equal magnitude but point in opposite directions, resulting in a net dipole moment of zero.",
  },
  {
    id: "vsepr-3",
    prompt: "What hybridization corresponds to a central atom with a steric number of 5 (such as in PCl₅)?",
    options: ["sp²", "sp³", "sp³d", "sp³d²"],
    answer: 2,
    explanation: "A steric number of 5 (trigonal bipyramidal electron geometry) involves one s orbital, three p orbitals, and one d orbital, giving sp³d hybridization.",
  },
  {
    id: "vsepr-4",
    prompt: "In a trigonal bipyramidal electron geometry (steric number 5), where do lone pairs prefer to reside to minimize repulsion?",
    options: [
      "In the equatorial positions (120° apart)",
      "In the axial positions (90° from equatorial)",
      "Alternating equally between axial and equatorial",
      "Directly inside the nucleus",
    ],
    answer: 0,
    explanation: "Equatorial positions have only two 90° neighbors, whereas axial positions have three 90° neighbors. Placing lone pairs equatorially minimizes high-energy 90° lone-pair repulsions.",
  },
  {
    id: "vsepr-5",
    prompt: "What is the molecular geometry of xenon tetrafluoride (XeF₄), which has 4 bonding pairs and 2 lone pairs on xenon (AX₄E₂)?",
    options: ["Tetrahedral", "Seesaw", "Square Planar", "Octahedral"],
    answer: 2,
    explanation: "Steric number 6 gives an octahedral electron geometry. The 2 lone pairs occupy opposite axial positions (180° apart), leaving the 4 fluorine atoms in a flat Square Planar arrangement.",
  },
];
